-- ============================================================
-- PART 5: INTELLIGENCE & AI LAYER
-- Insights, forecasts, benchmarks, chat history
-- ============================================================

-- ============================================================
-- AI INSIGHTS (recommendations generated by Meridian)
-- ============================================================
CREATE TABLE insights (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    org_id          UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    location_id     UUID REFERENCES locations(id) ON DELETE SET NULL,
    -- Insight details
    type            insight_type NOT NULL,
    title           TEXT NOT NULL,
    summary         TEXT NOT NULL,  -- human-readable summary
    details         JSONB NOT NULL DEFAULT '{}',  -- structured insight data
    -- Impact
    estimated_monthly_impact_cents INTEGER,  -- positive = revenue gain, negative = loss
    confidence_score DECIMAL(3, 2),  -- 0.00 to 1.00
    -- Related entities
    related_products UUID[] DEFAULT '{}',
    related_categories UUID[] DEFAULT '{}',
    -- Action tracking
    action_status   insight_action_status DEFAULT 'pending',
    actioned_by     UUID REFERENCES users(id),
    actioned_at     TIMESTAMPTZ,
    action_result   TEXT,
    -- Expiry (insights are time-sensitive)
    valid_until     TIMESTAMPTZ,
    is_active       BOOLEAN DEFAULT TRUE,
    -- Metadata
    model_version   TEXT,  -- which AI model generated this
    metadata        JSONB DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_insights_org ON insights(org_id, created_at DESC);
CREATE INDEX idx_insights_type ON insights(org_id, type);
CREATE INDEX idx_insights_active ON insights(org_id, is_active, action_status)
    WHERE is_active = TRUE;
CREATE INDEX idx_insights_impact ON insights(org_id, estimated_monthly_impact_cents DESC)
    WHERE is_active = TRUE;

-- ============================================================
-- MONEY LEFT ON TABLE SCORE (daily tracking)
-- ============================================================
CREATE TABLE money_left_scores (
    id              UUID DEFAULT uuid_generate_v4(),
    org_id          UUID NOT NULL,
    location_id     UUID,
    -- Score breakdown
    total_score_cents INTEGER NOT NULL,  -- total $ left on table
    components      JSONB NOT NULL DEFAULT '{}',
    -- Example components:
    -- {
    --   "underpriced_products": {"amount_cents": 120000, "products": [...]},
    --   "dead_stock": {"amount_cents": 45000, "products": [...]},
    --   "staffing_waste": {"amount_cents": 80000, "hours": [...]},
    --   "peak_hour_missed": {"amount_cents": 35000, "windows": [...]}
    -- }
    scored_at       TIMESTAMPTZ NOT NULL,
    model_version   TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, scored_at)
);

SELECT create_hypertable('money_left_scores', 'scored_at',
    chunk_time_interval => INTERVAL '1 month',
    if_not_exists => TRUE
);

CREATE INDEX idx_mls_org ON money_left_scores(org_id, scored_at DESC);

-- ============================================================
-- REVENUE FORECASTS
-- ============================================================
CREATE TABLE forecasts (
    id              UUID DEFAULT uuid_generate_v4(),
    org_id          UUID NOT NULL,
    location_id     UUID,
    -- Forecast details
    forecast_type   TEXT NOT NULL,  -- 'daily_revenue', 'weekly_revenue', 'product_demand'
    period_start    DATE NOT NULL,
    period_end      DATE NOT NULL,
    -- Values
    predicted_value_cents INTEGER NOT NULL,
    lower_bound_cents INTEGER,
    upper_bound_cents INTEGER,
    confidence_score DECIMAL(3, 2),
    -- Actual (filled in after the period)
    actual_value_cents INTEGER,
    accuracy_pct    DECIMAL(5, 2),  -- % accuracy after actuals
    -- Model info
    model_version   TEXT,
    features_used   JSONB DEFAULT '{}',
    generated_at    TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, generated_at)
);

SELECT create_hypertable('forecasts', 'generated_at',
    chunk_time_interval => INTERVAL '1 month',
    if_not_exists => TRUE
);

CREATE INDEX idx_forecasts_org ON forecasts(org_id, generated_at DESC);
CREATE INDEX idx_forecasts_period ON forecasts(org_id, period_start, period_end);

-- ============================================================
-- AI CHAT HISTORY (Business Advisor conversations)
-- ============================================================
CREATE TABLE chat_conversations (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    org_id          UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title           TEXT,  -- auto-generated from first message
    is_active       BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_convos_user ON chat_conversations(user_id, created_at DESC);

CREATE TABLE chat_messages (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    conversation_id UUID NOT NULL REFERENCES chat_conversations(id) ON DELETE CASCADE,
    org_id          UUID NOT NULL,
    -- Message
    role            TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content         TEXT NOT NULL,
    -- AI metadata
    tokens_used     INTEGER,
    model_used      TEXT,
    -- Referenced data (what data the AI accessed to answer)
    data_context    JSONB DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_messages_convo ON chat_messages(conversation_id, created_at);
CREATE INDEX idx_chat_messages_org ON chat_messages(org_id, created_at DESC);

-- ============================================================
-- WEEKLY REPORTS (generated snapshots)
-- ============================================================
CREATE TABLE weekly_reports (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    org_id          UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    location_id     UUID REFERENCES locations(id) ON DELETE SET NULL,
    -- Report period
    week_start      DATE NOT NULL,
    week_end        DATE NOT NULL,
    -- Report data (pre-computed for fast retrieval)
    report_data     JSONB NOT NULL DEFAULT '{}',
    -- Example structure:
    -- {
    --   "revenue": {"total": 4200000, "change_pct": 5.2, "vs_last_week": 4000000},
    --   "top_products": [...],
    --   "worst_products": [...],
    --   "recommendations": [...],
    --   "forecast_next_week": {...},
    --   "money_left_score": {...}
    -- }
    -- Delivery tracking
    emailed_to      TEXT[] DEFAULT '{}',
    emailed_at      TIMESTAMPTZ,
    viewed_at       TIMESTAMPTZ,
    -- Metadata
    model_version   TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_weekly_reports_org ON weekly_reports(org_id, week_start DESC);
CREATE UNIQUE INDEX idx_weekly_reports_unique ON weekly_reports(org_id, location_id, week_start);
