module.exports = {
  apps: [
    {
      name: "meridian-api",
      script: "/usr/local/bin/uvicorn",
      args: "src.api.app:app --host 0.0.0.0 --port 8000 --workers 4",
      cwd: "/root/Meridian",
      interpreter: "none",
      exec_mode: "fork",
      instances: 1,
      max_memory_restart: "512M",
      env: {
        PYTHONPATH: "/root/Meridian",
        ENABLE_LLM_INSIGHTS: "1",
        MERIDIAN_REASONING: "1",
        ENABLE_SWARM_TRAINING: "1",
        ENABLE_CANADA_INTELLIGENCE: "1",
        ENABLE_FINANCIAL_INTELLIGENCE: "1",
      },
    },
    {
      name: "celery-worker",
      script: "/usr/bin/bash",
      args: "-c 'celery -A src.workers.celery_app worker --loglevel=info -Q default,sync,analysis,reports --concurrency=8 --max-tasks-per-child=200'",
      cwd: "/root/Meridian",
      exec_mode: "fork",
      instances: 1,
      max_memory_restart: "400M",
    },
    {
      name: "celery-beat",
      script: "/usr/bin/bash",
      args: "-c 'celery -A src.workers.celery_app beat --loglevel=info'",
      cwd: "/root/Meridian",
      exec_mode: "fork",
      instances: 1,
      max_memory_restart: "200M",
    },
    {
      name: "deerflow",
      script: "/usr/bin/bash",
      args: "-c 'cd /root/Meridian/services/deerflow/backend && /root/.local/bin/uv run uvicorn app.api:app --host 0.0.0.0 --port 8004'",
      cwd: "/root/Meridian",
      exec_mode: "fork",
      instances: 1,
      max_memory_restart: "200M",
    },
    {
      name: "scraper",
      script: "/root/Meridian/scripts/scraper-daemon.py",
      cwd: "/root/Meridian",
      interpreter: "python3",
      exec_mode: "fork",
      instances: 1,
      max_memory_restart: "300M",
    },
    {
      name: "qwen-server",
      script: "/usr/bin/bash",
      args: "-c 'python3 -m llama_cpp.server --model /root/Meridian/data/models/Qwen2.5-7B-Instruct-Q4_K_M.gguf --host 0.0.0.0 --port 8002 --n_ctx 4096 --n_threads 4 --chat_format chatml'",
      cwd: "/root/Meridian",
      exec_mode: "fork",
      instances: 1,
      max_memory_restart: "12G",
    },
    {
      name: "garry",
      script: "/root/garry/garry_main.py",
      cwd: "/root/garry",
      interpreter: "python3",
      exec_mode: "fork",
      instances: 1,
      max_memory_restart: "200M",
    },
  ],
};
