GRANT ALL ON organizations TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON organizations TO authenticated;
GRANT SELECT ON organizations TO anon;
GRANT ALL ON locations TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON locations TO authenticated;
GRANT SELECT ON locations TO anon;
GRANT ALL ON users TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON users TO authenticated;
GRANT SELECT ON users TO anon;
GRANT ALL ON subscriptions TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON subscriptions TO authenticated;
GRANT SELECT ON subscriptions TO anon;
GRANT ALL ON pos_connections TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON pos_connections TO authenticated;
GRANT SELECT ON pos_connections TO anon;
GRANT ALL ON product_categories TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON product_categories TO authenticated;
GRANT SELECT ON product_categories TO anon;
GRANT ALL ON products TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON products TO authenticated;
GRANT SELECT ON products TO anon;
GRANT ALL ON transactions TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON transactions TO authenticated;
GRANT SELECT ON transactions TO anon;
GRANT ALL ON transaction_items TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON transaction_items TO authenticated;
GRANT SELECT ON transaction_items TO anon;
GRANT ALL ON inventory_snapshots TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON inventory_snapshots TO authenticated;
GRANT SELECT ON inventory_snapshots TO anon;
GRANT ALL ON suppliers TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON suppliers TO authenticated;
GRANT SELECT ON suppliers TO anon;
GRANT ALL ON scheduled_events TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON scheduled_events TO authenticated;
GRANT SELECT ON scheduled_events TO anon;
GRANT ALL ON notifications TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON notifications TO authenticated;
GRANT SELECT ON notifications TO anon;
GRANT ALL ON notification_rules TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON notification_rules TO authenticated;
GRANT SELECT ON notification_rules TO anon;
GRANT ALL ON insights TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON insights TO authenticated;
GRANT SELECT ON insights TO anon;
GRANT ALL ON money_left_scores TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON money_left_scores TO authenticated;
GRANT SELECT ON money_left_scores TO anon;
GRANT ALL ON forecasts TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON forecasts TO authenticated;
GRANT SELECT ON forecasts TO anon;
GRANT ALL ON chat_conversations TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON chat_conversations TO authenticated;
GRANT SELECT ON chat_conversations TO anon;
GRANT ALL ON chat_messages TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON chat_messages TO authenticated;
GRANT SELECT ON chat_messages TO anon;
GRANT ALL ON weekly_reports TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON weekly_reports TO authenticated;
GRANT SELECT ON weekly_reports TO anon;
GRANT ALL ON benchmark_profiles TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON benchmark_profiles TO authenticated;
GRANT SELECT ON benchmark_profiles TO anon;
GRANT ALL ON benchmark_snapshots TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON benchmark_snapshots TO authenticated;
GRANT SELECT ON benchmark_snapshots TO anon;
GRANT ALL ON industry_aggregates TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON industry_aggregates TO authenticated;
GRANT SELECT ON industry_aggregates TO anon;
GRANT ALL ON data_export_logs TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON data_export_logs TO authenticated;
GRANT SELECT ON data_export_logs TO anon;
GRANT ALL ON hourly_revenue TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON hourly_revenue TO authenticated;
GRANT SELECT ON hourly_revenue TO anon;
GRANT ALL ON daily_revenue TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON daily_revenue TO authenticated;
GRANT SELECT ON daily_revenue TO anon;
GRANT ALL ON daily_product_performance TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON daily_product_performance TO authenticated;
GRANT SELECT ON daily_product_performance TO anon;
GRANT ALL ON weekly_revenue TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON weekly_revenue TO authenticated;
GRANT SELECT ON weekly_revenue TO anon;

-- Grant usage on all sequences
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO service_role;