"""
DeerFlow bridge — connects Meridian's AI layer to the DeerFlow research agent.

DeerFlow runs as a FastAPI service at services/deerflow/backend/ on port 8001.
This client provides async methods for creating research threads, running
queries, and retrieving artifacts from the LangGraph-powered super-agent.
"""
import logging
import os
from typing import Any

import httpx

logger = logging.getLogger("meridian.services.deerflow")

DEERFLOW_URL = os.environ.get("DEERFLOW_URL", "http://localhost:8001")


class DeerFlowClient:

    def __init__(self, base_url: str = DEERFLOW_URL):
        self._base = base_url.rstrip("/")
        self._http: httpx.AsyncClient | None = None

    async def _client(self) -> httpx.AsyncClient:
        if self._http is None or self._http.is_closed:
            self._http = httpx.AsyncClient(
                base_url=self._base,
                timeout=60,
            )
        return self._http

    async def is_available(self) -> bool:
        try:
            c = await self._client()
            resp = await c.get("/api/models")
            return resp.status_code == 200
        except Exception:
            return False

    async def create_thread(self) -> str:
        """Create a new research thread. Returns thread_id."""
        c = await self._client()
        resp = await c.post("/api/langgraph/threads", json={})
        resp.raise_for_status()
        return resp.json()["thread_id"]

    async def research(
        self,
        query: str,
        thread_id: str | None = None,
    ) -> dict[str, Any]:
        """Run a research query through DeerFlow's lead agent."""
        if thread_id is None:
            thread_id = await self.create_thread()
        c = await self._client()
        resp = await c.post(
            f"/api/langgraph/threads/{thread_id}/runs",
            json={
                "assistant_id": "lead_agent",
                "input": {"messages": [{"role": "user", "content": query}]},
            },
            timeout=300,
        )
        resp.raise_for_status()
        return {"thread_id": thread_id, "result": resp.json()}

    async def get_artifacts(self, thread_id: str) -> list[dict]:
        """Retrieve artifacts generated by a research thread."""
        c = await self._client()
        resp = await c.get(f"/api/threads/{thread_id}/artifacts/")
        if resp.status_code == 404:
            return []
        resp.raise_for_status()
        return resp.json()

    async def get_memory(self) -> dict[str, Any]:
        """Get DeerFlow's memory status."""
        c = await self._client()
        resp = await c.get("/api/memory/status")
        resp.raise_for_status()
        return resp.json()

    async def close(self):
        if self._http and not self._http.is_closed:
            await self._http.aclose()


_client: DeerFlowClient | None = None


def get_deerflow() -> DeerFlowClient:
    global _client
    if _client is None:
        _client = DeerFlowClient()
    return _client
