// AUTOGENERATED - DO NOT MODIFY

// Timestamp changes on every export, ensuring the dev server detects a rebuild
export const BUILD_TIME = '2026-08-10 22:01:06.337324592 +0200 CEST m=+3.362082274';

// App manifest — consumed by the Dashboard to configure the app
export default {
  "$schema": "https://stripe.com/stripe-app.schema.json",
  "allowed_redirect_uris": [
    "https://api.meridian.tips/api/pos/stripe/callback"
  ],
  "distribution_type": "public",
  "icon": "./icon.png",
  "id": "tips.meridian.pos-analytics",
  "name": "Meridian POS Analytics",
  "permissions": [
    {
      "permission": "charge_read",
      "purpose": "Reads your charge and refund history to power Meridian's revenue analytics and reporting for your business."
    }
  ],
  "post_install_action": {
    "type": "external",
    "url": "https://meridian.tips/app/settings"
  },
  "sandbox_install_compatible": true,
  "stripe_api_access_type": "oauth",
  "version": "1.0.0"
};
