"""
POS System Registry — API configs for all 80 supported POS systems.

Each entry maps a system_key to a config dict consumed by GenericRESTConnector.
Systems with auth_type == "csv_only" have no API — use CSVImporter instead.

Config keys:
  base_url            Root URL (may contain {merchant_id} templates)
  auth_type           bearer | header | basic | query | oauth_client_credentials | csv_only
  auth_header_name    Header name when auth_type == "header"
  token_url           OAuth token endpoint for client_credentials flow
  extra_headers       Static headers merged into every request
  test_endpoint       Lightweight endpoint for connection test
  transactions_endpoint   GET transactions/orders
  catalog_endpoint    GET menu/catalog items
  employees_endpoint  GET employee list
  customers_endpoint  GET customer list
  order_create_endpoint   POST to create an order (phone agent)
  order_id_field      JSON key for order ID in create response
  order_payload_template  Jinja-style template dict for order POST body
  page_param          Pagination page parameter name
  limit_param         Pagination limit parameter name
  data_key            Top-level JSON key wrapping result arrays
  page_size           Records per page
  max_pages           Safety cap on pagination
  date_format         strftime format for date range params
  start_date_param    Query param name for start date
  end_date_param      Query param name for end date
  csv_columns         Column mapping for CSV import (csv_only systems)
  category            restaurant | retail | automotive | cannabis | multi_vertical
  supports_orders     Whether phone agent can push orders
  sms_fallback        Phone/email for non-API order forwarding
"""

SYSTEM_CONFIGS: dict[str, dict] = {

    # ═══════════════════════════════════════════════════════════
    # TIER 1 — Full OAuth, real-time webhooks
    # ═══════════════════════════════════════════════════════════

    "square": {
        "base_url": "https://connect.squareup.com/v2",
        "auth_type": "bearer",
        "test_endpoint": "/locations",
        "transactions_endpoint": "/orders/search",
        "catalog_endpoint": "/catalog/list",
        "employees_endpoint": "/team-members/search",
        "customers_endpoint": "/customers",
        "order_create_endpoint": "/orders",
        "order_id_field": "order.id",
        "page_param": "cursor",
        "limit_param": "limit",
        "data_key": None,
        "page_size": 100,
        "date_format": "%Y-%m-%dT%H:%M:%SZ",
        "start_date_param": "start_at",
        "end_date_param": "end_at",
        "category": "multi_vertical",
        "supports_orders": True,
    },
    "toast": {
        "base_url": "https://ws-api.toasttab.com",
        "auth_type": "oauth_client_credentials",
        "token_url": "https://ws-api.toasttab.com/authentication/v1/authentication/login",
        "extra_headers": {"Toast-Restaurant-External-ID": "{restaurant_id}"},
        "test_endpoint": "/restaurants/v1/restaurants/{restaurant_id}",
        "transactions_endpoint": "/orders/v2/orders",
        "catalog_endpoint": "/menus/v2/menus",
        "employees_endpoint": "/labor/v1/employees",
        "customers_endpoint": "/customers/v1/customers",
        "order_create_endpoint": "/orders/v2/orders",
        "order_id_field": "guid",
        "page_param": "page",
        "limit_param": "pageSize",
        "data_key": None,
        "page_size": 100,
        "date_format": "%Y-%m-%dT%H:%M:%S.000+0000",
        "start_date_param": "startDate",
        "end_date_param": "endDate",
        "category": "restaurant",
        "supports_orders": True,
    },
    "clover": {
        "base_url": "https://api.clover.com/v3/merchants/{merchant_id}",
        "auth_type": "bearer",
        "test_endpoint": "",
        "transactions_endpoint": "/orders",
        "catalog_endpoint": "/items",
        "employees_endpoint": "/employees",
        "customers_endpoint": "/customers",
        "order_create_endpoint": "/atomic_order/orders",
        "order_id_field": "id",
        "page_param": "offset",
        "limit_param": "limit",
        "data_key": "elements",
        "page_size": 100,
        "date_format": "%Y-%m-%dT%H:%M:%SZ",
        "start_date_param": "filter",
        "end_date_param": "filter",
        "category": "multi_vertical",
        "supports_orders": True,
    },

    # ═══════════════════════════════════════════════════════════
    # TIER 2 — Good APIs (OAuth or API key)
    # ═══════════════════════════════════════════════════════════

    "lightspeed-restaurant": {
        "base_url": "https://api.lightspeedrestaurant.com/v1",
        "auth_type": "bearer",
        "test_endpoint": "/businesses",
        "transactions_endpoint": "/transactions",
        "catalog_endpoint": "/items",
        "employees_endpoint": "/employees",
        "customers_endpoint": "/customers",
        "order_create_endpoint": "/orders",
        "order_id_field": "id",
        "data_key": "data",
        "category": "restaurant",
        "supports_orders": True,
    },
    "lightspeed-retail": {
        "base_url": "https://api.lightspeedapp.com/API/V3/Account/{account_id}",
        "auth_type": "bearer",
        "test_endpoint": "",
        "transactions_endpoint": "/Sale.json",
        "catalog_endpoint": "/Item.json",
        "employees_endpoint": "/Employee.json",
        "customers_endpoint": "/Customer.json",
        "data_key": "Sale",
        "category": "retail",
        "supports_orders": False,
    },
    "spoton": {
        "base_url": "https://api.spoton.com/v1",
        "auth_type": "bearer",
        "test_endpoint": "/merchants/me",
        "transactions_endpoint": "/transactions",
        "catalog_endpoint": "/menu/items",
        "employees_endpoint": "/employees",
        "customers_endpoint": "/customers",
        "order_create_endpoint": "/orders",
        "order_id_field": "orderId",
        "data_key": "data",
        "category": "restaurant",
        "supports_orders": True,
    },
    "revel": {
        "base_url": "https://{domain}.revelup.com/resources",
        "auth_type": "header",
        "auth_header_name": "API-AUTHENTICATION",
        "test_endpoint": "/Establishment/",
        "transactions_endpoint": "/Order/",
        "catalog_endpoint": "/Product/",
        "employees_endpoint": "/Employee/",
        "customers_endpoint": "/Customer/",
        "order_create_endpoint": "/Order/",
        "order_id_field": "id",
        "page_param": "offset",
        "limit_param": "limit",
        "data_key": "objects",
        "page_size": 200,
        "category": "restaurant",
        "supports_orders": True,
    },
    "touchbistro": {
        "base_url": "https://cloud.touchbistro.com/api/v1",
        "auth_type": "header",
        "auth_header_name": "Authorization",
        "test_endpoint": "/restaurants/{restaurant_id}",
        "transactions_endpoint": "/restaurants/{restaurant_id}/orders",
        "catalog_endpoint": "/restaurants/{restaurant_id}/menu-items",
        "employees_endpoint": "/restaurants/{restaurant_id}/staff",
        "data_key": "data",
        "category": "restaurant",
        "supports_orders": False,
    },
    "aloha": {
        "base_url": "https://api.ncr.com/asr/v2",
        "auth_type": "header",
        "auth_header_name": "X-Api-Key",
        "extra_headers": {"nep-organization": "{org_id}"},
        "test_endpoint": "/sites",
        "transactions_endpoint": "/orders",
        "catalog_endpoint": "/items",
        "employees_endpoint": "/employees",
        "data_key": "items",
        "category": "restaurant",
        "supports_orders": False,
    },
    "micros": {
        "base_url": "https://api.oracle.com/food-and-beverage/v1",
        "auth_type": "oauth_client_credentials",
        "token_url": "https://login.oracle.com/oauth/token",
        "test_endpoint": "/organizations/{org_id}/properties",
        "transactions_endpoint": "/organizations/{org_id}/transactions",
        "catalog_endpoint": "/organizations/{org_id}/menu-items",
        "employees_endpoint": "/organizations/{org_id}/employees",
        "data_key": "items",
        "category": "restaurant",
        "supports_orders": False,
    },
    "heartland": {
        "base_url": "https://api.heartlandpos.com/v1",
        "auth_type": "bearer",
        "test_endpoint": "/merchants/{merchant_id}",
        "transactions_endpoint": "/merchants/{merchant_id}/transactions",
        "catalog_endpoint": "/merchants/{merchant_id}/items",
        "employees_endpoint": "/merchants/{merchant_id}/employees",
        "customers_endpoint": "/merchants/{merchant_id}/customers",
        "order_create_endpoint": "/merchants/{merchant_id}/orders",
        "order_id_field": "orderId",
        "data_key": "data",
        "category": "restaurant",
        "supports_orders": True,
    },
    "tekmetric": {
        "base_url": "https://sandbox.tekmetric.com/api/v1",
        "auth_type": "header",
        "auth_header_name": "Authorization",
        "test_endpoint": "/shops",
        "transactions_endpoint": "/repair-orders",
        "catalog_endpoint": "/services",
        "employees_endpoint": "/employees",
        "customers_endpoint": "/customers",
        "order_create_endpoint": "/repair-orders",
        "order_id_field": "id",
        "data_key": "content",
        "page_param": "page",
        "limit_param": "size",
        "page_size": 100,
        "date_format": "%Y-%m-%dT%H:%M:%SZ",
        "start_date_param": "updatedDateStart",
        "end_date_param": "updatedDateEnd",
        "category": "automotive",
        "supports_orders": True,
    },
    "shop-ware": {
        "base_url": "https://app.shop-ware.com/api/v1",
        "auth_type": "bearer",
        "test_endpoint": "/shops",
        "transactions_endpoint": "/repair_orders",
        "catalog_endpoint": "/services",
        "employees_endpoint": "/technicians",
        "customers_endpoint": "/customers",
        "order_create_endpoint": "/repair_orders",
        "order_id_field": "id",
        "data_key": "results",
        "page_param": "page",
        "limit_param": "per_page",
        "date_format": "%Y-%m-%d",
        "start_date_param": "updated_after",
        "end_date_param": "updated_before",
        "category": "automotive",
        "supports_orders": True,
    },
    "shopmonkey": {
        "base_url": "https://api.shopmonkey.cloud/v3",
        "auth_type": "header",
        "auth_header_name": "Authorization",
        "test_endpoint": "/locations",
        "transactions_endpoint": "/orders",
        "catalog_endpoint": "/services",
        "employees_endpoint": "/users",
        "customers_endpoint": "/customers",
        "order_create_endpoint": "/orders",
        "order_id_field": "id",
        "data_key": "data",
        "category": "automotive",
        "supports_orders": True,
    },
    "qu-pos": {
        "base_url": "https://api.qupos.com/v2",
        "auth_type": "bearer",
        "test_endpoint": "/locations",
        "transactions_endpoint": "/orders",
        "catalog_endpoint": "/menu/items",
        "employees_endpoint": "/employees",
        "customers_endpoint": "/customers",
        "order_create_endpoint": "/orders",
        "order_id_field": "orderId",
        "data_key": "data",
        "category": "restaurant",
        "supports_orders": True,
    },
    "skytab": {
        "base_url": "https://api.shift4.com/v1",
        "auth_type": "bearer",
        "test_endpoint": "/merchants/{merchant_id}",
        "transactions_endpoint": "/merchants/{merchant_id}/transactions",
        "catalog_endpoint": "/merchants/{merchant_id}/items",
        "employees_endpoint": "/merchants/{merchant_id}/employees",
        "data_key": "data",
        "category": "restaurant",
        "supports_orders": False,
    },
    "upserve": {
        "base_url": "https://api.upserve.com/v2",
        "auth_type": "bearer",
        "test_endpoint": "/restaurants",
        "transactions_endpoint": "/checks",
        "catalog_endpoint": "/menu-items",
        "employees_endpoint": "/employees",
        "customers_endpoint": "/guests",
        "data_key": "data",
        "category": "restaurant",
        "supports_orders": False,
    },
    "dutchie-pos": {
        "base_url": "https://plus.dutchie.com/api/v1",
        "auth_type": "bearer",
        "test_endpoint": "/retailers/{retailer_id}",
        "transactions_endpoint": "/retailers/{retailer_id}/orders",
        "catalog_endpoint": "/retailers/{retailer_id}/products",
        "employees_endpoint": "/retailers/{retailer_id}/employees",
        "customers_endpoint": "/retailers/{retailer_id}/customers",
        "order_create_endpoint": "/retailers/{retailer_id}/orders",
        "order_id_field": "id",
        "data_key": "data",
        "category": "cannabis",
        "supports_orders": True,
    },

    # ═══════════════════════════════════════════════════════════
    # TIER 3 — Mixed (some have APIs, some CSV-only)
    # ═══════════════════════════════════════════════════════════

    "shopify-pos": {
        "base_url": "https://{shop_domain}/admin/api/2024-01",
        "auth_type": "header",
        "auth_header_name": "X-Shopify-Access-Token",
        "test_endpoint": "/shop.json",
        "transactions_endpoint": "/orders.json",
        "catalog_endpoint": "/products.json",
        "employees_endpoint": "/users.json",
        "customers_endpoint": "/customers.json",
        "order_create_endpoint": "/orders.json",
        "order_id_field": "order.id",
        "data_key": "orders",
        "page_param": "page_info",
        "limit_param": "limit",
        "page_size": 250,
        "date_format": "%Y-%m-%dT%H:%M:%S-00:00",
        "start_date_param": "created_at_min",
        "end_date_param": "created_at_max",
        "category": "retail",
        "supports_orders": True,
    },
    "stripe-terminal": {
        "base_url": "https://api.stripe.com/v1",
        "auth_type": "basic",
        "test_endpoint": "/balance",
        "transactions_endpoint": "/payment_intents",
        "catalog_endpoint": "/products",
        "customers_endpoint": "/customers",
        "data_key": "data",
        "page_param": "starting_after",
        "limit_param": "limit",
        "page_size": 100,
        "date_format": "%s",
        "start_date_param": "created[gte]",
        "end_date_param": "created[lte]",
        "category": "multi_vertical",
        "supports_orders": False,
    },
    "paypal-zettle": {
        "base_url": "https://purchase.izettle.com",
        "auth_type": "bearer",
        "test_endpoint": "/users/self",
        "transactions_endpoint": "/purchases/v2",
        "catalog_endpoint": "/organizations/{org_id}/products",
        "data_key": "purchases",
        "date_format": "%Y-%m-%dT%H:%M:%S.000Z",
        "start_date_param": "startDate",
        "end_date_param": "endDate",
        "category": "retail",
        "supports_orders": False,
    },
    "sumup": {
        "base_url": "https://api.sumup.com/v0.1",
        "auth_type": "bearer",
        "test_endpoint": "/me",
        "transactions_endpoint": "/me/transactions/history",
        "data_key": "items",
        "category": "retail",
        "supports_orders": False,
    },
    "lavu": {
        "base_url": "https://api.lavu.com/v1",
        "auth_type": "header",
        "auth_header_name": "X-Api-Key",
        "test_endpoint": "/locations",
        "transactions_endpoint": "/orders",
        "catalog_endpoint": "/menus/items",
        "employees_endpoint": "/employees",
        "order_create_endpoint": "/orders",
        "order_id_field": "id",
        "data_key": "data",
        "category": "restaurant",
        "supports_orders": True,
    },
    "cake": {
        "base_url": "https://api.cake.net/v1",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Order ID",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Items",
            "payment_method": "Payment Type",
        },
        "category": "restaurant",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "harbortouch": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Trans #",
            "timestamp": "Date/Time",
            "total_cents": "Amount",
            "items": "Description",
            "payment_method": "Tender",
        },
        "category": "multi_vertical",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "aldelo": {
        "base_url": "https://api.aldelo.com/v1",
        "auth_type": "header",
        "auth_header_name": "X-API-Key",
        "test_endpoint": "/restaurants",
        "transactions_endpoint": "/transactions",
        "catalog_endpoint": "/menus",
        "employees_endpoint": "/employees",
        "data_key": "data",
        "category": "restaurant",
        "supports_orders": False,
    },
    "focus-pos": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Check Number",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Item Name",
            "payment_method": "Payment Method",
            "employee_name": "Server",
        },
        "category": "restaurant",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "digital-dining": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Ticket #",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Menu Item",
            "payment_method": "Pay Type",
        },
        "category": "restaurant",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "future-pos": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Receipt Number",
            "timestamp": "Transaction Date",
            "total_cents": "Grand Total",
            "items": "Item Description",
            "payment_method": "Tender Type",
        },
        "category": "restaurant",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "pixelpoint": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Transaction ID",
            "timestamp": "Date Time",
            "total_cents": "Total",
            "items": "Item",
            "payment_method": "Payment",
        },
        "category": "restaurant",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "mitchell1": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "RO Number",
            "timestamp": "Date Closed",
            "total_cents": "Total",
            "items": "Labor Description",
            "vin": "VIN",
            "labor_hours": "Hours",
            "technician": "Technician",
        },
        "category": "automotive",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "autofluent": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Invoice #",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Description",
            "vin": "VIN",
            "labor_hours": "Labor Hrs",
            "technician": "Tech",
        },
        "category": "automotive",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "shop-boss": {
        "base_url": "https://app.shopboss.net/api/v1",
        "auth_type": "header",
        "auth_header_name": "X-Api-Key",
        "test_endpoint": "/shops",
        "transactions_endpoint": "/work-orders",
        "catalog_endpoint": "/services",
        "customers_endpoint": "/customers",
        "data_key": "data",
        "category": "automotive",
        "supports_orders": False,
    },
    "ro-writer": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "RO#",
            "timestamp": "Close Date",
            "total_cents": "RO Total",
            "items": "Service Line",
            "vin": "VIN",
            "labor_hours": "Labor Hours",
            "technician": "Technician",
        },
        "category": "automotive",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "protractor": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Invoice Number",
            "timestamp": "Invoice Date",
            "total_cents": "Invoice Total",
            "items": "Line Item",
            "vin": "VIN",
            "labor_hours": "Labour Hours",
            "technician": "Assigned Tech",
        },
        "category": "automotive",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "alldata-manage": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Work Order #",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Description",
            "vin": "VIN",
            "labor_hours": "Hours",
        },
        "category": "automotive",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "napa-tracs": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "RO Number",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Service",
            "vin": "VIN",
            "labor_hours": "Hours",
            "technician": "Technician",
        },
        "category": "automotive",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "rezku": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Order #",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Item Name",
            "payment_method": "Payment Type",
        },
        "category": "restaurant",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "talech": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Receipt #",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Item",
            "payment_method": "Payment Method",
        },
        "category": "multi_vertical",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "loyverse": {
        "base_url": "https://api.loyverse.com/v1.0",
        "auth_type": "bearer",
        "test_endpoint": "/merchant",
        "transactions_endpoint": "/receipts",
        "catalog_endpoint": "/items",
        "employees_endpoint": "/employees",
        "customers_endpoint": "/customers",
        "data_key": "receipts",
        "page_param": "cursor",
        "limit_param": "limit",
        "page_size": 250,
        "date_format": "%Y-%m-%dT%H:%M:%S.000Z",
        "start_date_param": "after",
        "end_date_param": "before",
        "category": "multi_vertical",
        "supports_orders": False,
    },
    "gloria-food": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Order ID",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Items Ordered",
            "payment_method": "Payment",
            "customer_name": "Customer Name",
        },
        "category": "restaurant",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "korona-pos": {
        "base_url": "https://api.koronacloud.com/web/api/v3/accounts/{account_id}",
        "auth_type": "basic",
        "test_endpoint": "",
        "transactions_endpoint": "/receipts",
        "catalog_endpoint": "/products",
        "employees_endpoint": "/cashiers",
        "customers_endpoint": "/customers",
        "data_key": "results",
        "category": "retail",
        "supports_orders": False,
    },
    "hike-pos": {
        "base_url": "https://api.hikeup.com",
        "auth_type": "bearer",
        "test_endpoint": "/api/v1/stores",
        "transactions_endpoint": "/api/v1/sales",
        "catalog_endpoint": "/api/v1/products",
        "customers_endpoint": "/api/v1/customers",
        "data_key": "data",
        "category": "retail",
        "supports_orders": False,
    },
    "rain-pos": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Transaction #",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Item Description",
            "payment_method": "Payment Type",
        },
        "category": "retail",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "bindo-pos": {
        "base_url": "https://api.bfriendo.com/v2",
        "auth_type": "header",
        "auth_header_name": "X-Api-Key",
        "test_endpoint": "/stores",
        "transactions_endpoint": "/orders",
        "catalog_endpoint": "/products",
        "customers_endpoint": "/customers",
        "data_key": "data",
        "category": "retail",
        "supports_orders": False,
    },
    "erply": {
        "base_url": "https://{account_code}.erply.com/api",
        "auth_type": "header",
        "auth_header_name": "sessionKey",
        "test_endpoint": "/?request=getConfParameters",
        "transactions_endpoint": "/?request=getSalesDocuments",
        "catalog_endpoint": "/?request=getProducts",
        "employees_endpoint": "/?request=getEmployees",
        "customers_endpoint": "/?request=getCustomers",
        "data_key": "records",
        "category": "retail",
        "supports_orders": False,
    },
    "accu-pos": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Transaction ID",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Description",
            "payment_method": "Payment Method",
        },
        "category": "multi_vertical",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "retail-edge": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Invoice",
            "timestamp": "Date",
            "total_cents": "Amount",
            "items": "Description",
            "payment_method": "Payment",
        },
        "category": "retail",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "php-pos": {
        "base_url": "https://{domain}/index.php/api/v1",
        "auth_type": "header",
        "auth_header_name": "x-api-key",
        "test_endpoint": "/info",
        "transactions_endpoint": "/sales",
        "catalog_endpoint": "/items",
        "employees_endpoint": "/employees",
        "customers_endpoint": "/customers",
        "data_key": None,
        "category": "retail",
        "supports_orders": False,
    },
    "cashier-live": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Receipt #",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Product",
            "payment_method": "Payment",
        },
        "category": "retail",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "pos-nation": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Sale ID",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Item Name",
            "payment_method": "Tender Type",
        },
        "category": "cannabis",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "cova-pos": {
        "base_url": "https://api.covasoftware.com/v1",
        "auth_type": "header",
        "auth_header_name": "Authorization",
        "test_endpoint": "/companies",
        "transactions_endpoint": "/sales/invoices",
        "catalog_endpoint": "/catalog/products",
        "employees_endpoint": "/employees",
        "customers_endpoint": "/customers",
        "data_key": "data",
        "category": "cannabis",
        "supports_orders": False,
    },
    "treez": {
        "base_url": "https://api.treez.io/v2.0/dispensary/{dispensary_id}",
        "auth_type": "bearer",
        "test_endpoint": "",
        "transactions_endpoint": "/tickets",
        "catalog_endpoint": "/products",
        "employees_endpoint": "/budtenders",
        "customers_endpoint": "/customers",
        "data_key": "data",
        "category": "cannabis",
        "supports_orders": False,
    },
    "flowhub": {
        "base_url": "https://api.flowhub.co/v1",
        "auth_type": "bearer",
        "test_endpoint": "/locations",
        "transactions_endpoint": "/transactions",
        "catalog_endpoint": "/inventory",
        "employees_endpoint": "/employees",
        "customers_endpoint": "/members",
        "data_key": "data",
        "category": "cannabis",
        "supports_orders": False,
    },
    "meadow": {
        "base_url": "https://api.getmeadow.com/api/v2",
        "auth_type": "header",
        "auth_header_name": "X-Api-Key",
        "test_endpoint": "/dispensaries",
        "transactions_endpoint": "/orders",
        "catalog_endpoint": "/products",
        "customers_endpoint": "/patients",
        "data_key": "data",
        "category": "cannabis",
        "supports_orders": False,
    },
    "blaze-pos": {
        "base_url": "https://api.blaze.me/api/v1",
        "auth_type": "header",
        "auth_header_name": "Authorization",
        "test_endpoint": "/partner/store",
        "transactions_endpoint": "/partner/transactions",
        "catalog_endpoint": "/partner/products",
        "customers_endpoint": "/partner/members",
        "data_key": "values",
        "category": "cannabis",
        "supports_orders": False,
    },

    # ═══════════════════════════════════════════════════════════
    # TIER 4 — Enterprise / SOAP / Legacy
    # ═══════════════════════════════════════════════════════════

    "brink": {
        "base_url": "https://api.brinkpos.net/v1",
        "auth_type": "header",
        "auth_header_name": "X-API-Key",
        "test_endpoint": "/locations",
        "transactions_endpoint": "/orders",
        "catalog_endpoint": "/menus",
        "data_key": "data",
        "category": "restaurant",
        "supports_orders": False,
    },
    "simphony": {
        "base_url": "https://api.oracle.com/food-and-beverage/v1",
        "auth_type": "oauth_client_credentials",
        "token_url": "https://login.oracle.com/oauth/token",
        "test_endpoint": "/organizations/{org_id}/locations",
        "transactions_endpoint": "/organizations/{org_id}/checks",
        "catalog_endpoint": "/organizations/{org_id}/menu-items",
        "employees_endpoint": "/organizations/{org_id}/employees",
        "data_key": "items",
        "category": "restaurant",
        "supports_orders": False,
    },
    "northstar": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Check #",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Item",
            "payment_method": "Payment",
            "employee_name": "Server",
        },
        "category": "restaurant",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "xenial": {
        "base_url": "https://api.xenial.com/v1",
        "auth_type": "header",
        "auth_header_name": "X-Api-Key",
        "test_endpoint": "/sites",
        "transactions_endpoint": "/transactions",
        "catalog_endpoint": "/menu-items",
        "data_key": "data",
        "category": "restaurant",
        "supports_orders": False,
    },
    "squirrel": {
        "base_url": "https://api.squirrelsystems.com/v1",
        "auth_type": "header",
        "auth_header_name": "X-Api-Key",
        "test_endpoint": "/properties",
        "transactions_endpoint": "/checks",
        "catalog_endpoint": "/menu-items",
        "employees_endpoint": "/employees",
        "data_key": "data",
        "category": "restaurant",
        "supports_orders": False,
    },
    "agilysys": {
        "base_url": "https://api.agilysys.com/v1",
        "auth_type": "header",
        "auth_header_name": "X-Api-Key",
        "test_endpoint": "/properties",
        "transactions_endpoint": "/transactions",
        "catalog_endpoint": "/items",
        "data_key": "data",
        "category": "restaurant",
        "supports_orders": False,
    },
    "omnique": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Invoice Number",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Description",
            "vin": "VIN",
            "labor_hours": "Labor",
            "technician": "Tech",
        },
        "category": "automotive",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "autovitals": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "RO #",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Service",
            "vin": "VIN",
        },
        "category": "automotive",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "tire-master": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Invoice #",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Service Description",
            "vin": "VIN",
            "technician": "Technician",
        },
        "category": "automotive",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "bolt-on": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "RO #",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Service",
            "vin": "VIN",
        },
        "category": "automotive",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "olo": {
        "base_url": "https://ordering-api.olo.com/v1.1",
        "auth_type": "header",
        "auth_header_name": "Authorization",
        "test_endpoint": "/restaurants",
        "transactions_endpoint": "/orders",
        "catalog_endpoint": "/restaurants/{restaurant_id}/menu",
        "data_key": None,
        "category": "restaurant",
        "supports_orders": True,
        "order_create_endpoint": "/restaurants/{restaurant_id}/orders",
        "order_id_field": "id",
    },
    "ncr-voyix": {
        "base_url": "https://gateway.ncrcloud.com",
        "auth_type": "oauth_client_credentials",
        "token_url": "https://gateway.ncrcloud.com/security/authentication/login",
        "extra_headers": {"nep-organization": "{org_id}"},
        "test_endpoint": "/site/sites/find-by-criteria",
        "transactions_endpoint": "/transaction-document/transaction-documents/find-by-criteria",
        "catalog_endpoint": "/catalog/items/find-by-criteria",
        "data_key": "pageContent",
        "category": "multi_vertical",
        "supports_orders": False,
    },
    "woo-pos": {
        "base_url": "https://{domain}/wp-json/wc/v3",
        "auth_type": "basic",
        "test_endpoint": "/system_status",
        "transactions_endpoint": "/orders",
        "catalog_endpoint": "/products",
        "customers_endpoint": "/customers",
        "data_key": None,
        "page_param": "page",
        "limit_param": "per_page",
        "page_size": 100,
        "date_format": "%Y-%m-%dT%H:%M:%S",
        "start_date_param": "after",
        "end_date_param": "before",
        "category": "retail",
        "supports_orders": True,
        "order_create_endpoint": "/orders",
        "order_id_field": "id",
    },
    "openbravo": {
        "base_url": "https://{domain}/openbravo/org.openbravo.service.json.jsonrest",
        "auth_type": "basic",
        "test_endpoint": "/ADUser",
        "transactions_endpoint": "/FIN_Payment",
        "catalog_endpoint": "/Product",
        "employees_endpoint": "/ADUser",
        "customers_endpoint": "/BusinessPartner",
        "data_key": "response.data",
        "category": "multi_vertical",
        "supports_orders": False,
    },
    "biotrack": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Transaction ID",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Product Name",
            "metrc_tag": "METRC Tag",
            "compliance_id": "License Number",
        },
        "category": "cannabis",
        "supports_orders": False,
        "sms_fallback": True,
    },
    "leaf-logix": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Sale ID",
            "timestamp": "Sale Date",
            "total_cents": "Total",
            "items": "Product Name",
            "metrc_tag": "METRC Tag",
            "compliance_id": "State License",
        },
        "category": "cannabis",
        "supports_orders": False,
        "sms_fallback": True,
    },

    # ═══════════════════════════════════════════════════════════
    # TIER 5 — International / Niche
    # ═══════════════════════════════════════════════════════════

    "epos-now": {
        "base_url": "https://api.eposnowhq.com/api/v4",
        "auth_type": "bearer",
        "test_endpoint": "/device",
        "transactions_endpoint": "/transaction",
        "catalog_endpoint": "/product",
        "employees_endpoint": "/staff",
        "customers_endpoint": "/customer",
        "data_key": None,
        "category": "multi_vertical",
        "supports_orders": False,
    },
    "izettle": {
        "base_url": "https://purchase.izettle.com",
        "auth_type": "bearer",
        "test_endpoint": "/users/self",
        "transactions_endpoint": "/purchases/v2",
        "catalog_endpoint": "/organizations/{org_id}/products",
        "data_key": "purchases",
        "category": "retail",
        "supports_orders": False,
    },
    "tyro": {
        "base_url": "https://api.tyro.com/connect/v1",
        "auth_type": "header",
        "auth_header_name": "X-Api-Key",
        "test_endpoint": "/merchants/{merchant_id}",
        "transactions_endpoint": "/merchants/{merchant_id}/transactions",
        "data_key": "data",
        "category": "multi_vertical",
        "supports_orders": False,
    },
    "poster-pos": {
        "base_url": "https://joinposter.com/api",
        "auth_type": "query",
        "test_endpoint": "/settings.getSettings",
        "transactions_endpoint": "/dash.getTransactions",
        "catalog_endpoint": "/menu.getProducts",
        "employees_endpoint": "/access.getEmployees",
        "customers_endpoint": "/clients.getClients",
        "data_key": "response",
        "category": "restaurant",
        "supports_orders": False,
    },
    "iiko": {
        "base_url": "https://api-ru.iiko.services/api/1",
        "auth_type": "bearer",
        "test_endpoint": "/organizations",
        "transactions_endpoint": "/deliveries/by_delivery_date_and_status",
        "catalog_endpoint": "/nomenclature",
        "data_key": None,
        "category": "restaurant",
        "supports_orders": True,
        "order_create_endpoint": "/deliveries/create",
        "order_id_field": "orderInfo.id",
    },
    "posist": {
        "base_url": "https://api.posist.com/x/v1",
        "auth_type": "header",
        "auth_header_name": "X-Api-Key",
        "test_endpoint": "/restaurant",
        "transactions_endpoint": "/tabs",
        "catalog_endpoint": "/menuitems",
        "employees_endpoint": "/users",
        "data_key": "data",
        "category": "restaurant",
        "supports_orders": False,
    },
    "petpooja": {
        "base_url": "https://api.petpooja.com/v2",
        "auth_type": "header",
        "auth_header_name": "X-Api-Key",
        "test_endpoint": "/restaurants",
        "transactions_endpoint": "/orders",
        "catalog_endpoint": "/menu",
        "data_key": "data",
        "category": "restaurant",
        "supports_orders": True,
        "order_create_endpoint": "/orders",
        "order_id_field": "orderid",
    },
    "indica-online": {
        "base_url": "",
        "auth_type": "csv_only",
        "csv_columns": {
            "transaction_id": "Order #",
            "timestamp": "Date",
            "total_cents": "Total",
            "items": "Product",
            "metrc_tag": "Track ID",
            "compliance_id": "License",
        },
        "category": "cannabis",
        "supports_orders": False,
        "sms_fallback": True,
    },
}


def get_connector_config(system_key: str) -> dict | None:
    return SYSTEM_CONFIGS.get(system_key)


def get_all_configs() -> dict[str, dict]:
    return dict(SYSTEM_CONFIGS)


def get_api_systems() -> list[str]:
    return [k for k, v in SYSTEM_CONFIGS.items() if v.get("auth_type") != "csv_only"]


def get_csv_only_systems() -> list[str]:
    return [k for k, v in SYSTEM_CONFIGS.items() if v.get("auth_type") == "csv_only"]


def get_order_capable_systems() -> list[str]:
    return [k for k, v in SYSTEM_CONFIGS.items() if v.get("supports_orders")]


def get_systems_by_category(category: str) -> list[str]:
    return [k for k, v in SYSTEM_CONFIGS.items() if v.get("category") == category]
