import jsPDF from 'jspdf'
import type { ScheduleShift, ScheduleStaffMember } from '@/lib/agent-data'

const DAY_NAMES = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
const MARGIN = 15
const BG = '#0a0f0d'
const CARD = '#0f1512'
const BORDER = '#1a2420'
const ACCENT = '#1A8FD6'
const TEXT = '#e8ede8'
const MUTED = '#6b7a74'

function addDays(date: Date, days: number): Date {
  const d = new Date(date)
  d.setDate(d.getDate() + days)
  return d
}

function formatWeekRange(start: Date): string {
  const end = addDays(start, 6)
  const opts: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric', year: 'numeric' }
  return `${start.toLocaleDateString('en-US', opts)} – ${end.toLocaleDateString('en-US', opts)}`
}

function setColor(doc: jsPDF, hex: string) {
  const r = parseInt(hex.slice(1, 3), 16)
  const g = parseInt(hex.slice(3, 5), 16)
  const b = parseInt(hex.slice(5, 7), 16)
  doc.setTextColor(r, g, b)
}

function setFillColor(doc: jsPDF, hex: string) {
  const r = parseInt(hex.slice(1, 3), 16)
  const g = parseInt(hex.slice(3, 5), 16)
  const b = parseInt(hex.slice(5, 7), 16)
  doc.setFillColor(r, g, b)
}

function setDrawColor(doc: jsPDF, hex: string) {
  const r = parseInt(hex.slice(1, 3), 16)
  const g = parseInt(hex.slice(3, 5), 16)
  const b = parseInt(hex.slice(5, 7), 16)
  doc.setDrawColor(r, g, b)
}

export interface SchedulePdfInput {
  shifts: ScheduleShift[]
  staff: ScheduleStaffMember[]
  weekStartDate: Date
}

export async function generateSchedulePdf(input: SchedulePdfInput): Promise<Blob> {
  const { shifts, staff, weekStartDate } = input
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape' })
  const pageW = 297
  const pageH = 210
  const contentW = pageW - MARGIN * 2

  const staffMap = new Map<string, ScheduleStaffMember>()
  staff.forEach(s => staffMap.set(s.id, s))

  // Only include assigned, non-recommended shifts
  const realShifts = shifts.filter(s => !s.isRecommended && s.staffMemberId)

  // Unique staff that have shifts
  const staffWithShifts = staff.filter(s =>
    realShifts.some(sh => sh.staffMemberId === s.id)
  )

  // Background
  setFillColor(doc, BG)
  doc.rect(0, 0, pageW, pageH, 'F')

  // Header
  let y = 18
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  setColor(doc, ACCENT)
  doc.text(`Weekly Schedule — ${formatWeekRange(weekStartDate)}`, pageW / 2, y, { align: 'center' })

  y += 10

  // Table dimensions
  const nameColW = 30
  const dayColW = (contentW - nameColW) / 7
  const rowH = 9
  const headerH = 8

  // Table header — day names
  let x = MARGIN
  setFillColor(doc, '#142018')
  setDrawColor(doc, BORDER)
  doc.rect(x, y, nameColW, headerH, 'FD')
  doc.setFontSize(7)
  doc.setFont('helvetica', 'bold')
  setColor(doc, MUTED)
  doc.text('Staff', x + 2, y + 5.5)

  x += nameColW
  for (let d = 0; d < 7; d++) {
    setFillColor(doc, '#142018')
    doc.rect(x, y, dayColW, headerH, 'FD')
    setColor(doc, ACCENT)
    const dayDate = addDays(weekStartDate, d)
    const label = `${DAY_NAMES[d].slice(0, 3)} ${dayDate.getDate()}`
    doc.text(label, x + dayColW / 2, y + 5.5, { align: 'center' })
    x += dayColW
  }

  y += headerH

  // Staff rows
  const staffList = staffWithShifts.length > 0 ? staffWithShifts : staff
  for (const member of staffList) {
    if (y + rowH > pageH - 20) break // prevent overflow

    x = MARGIN
    setFillColor(doc, CARD)
    setDrawColor(doc, BORDER)
    doc.rect(x, y, nameColW, rowH, 'FD')
    doc.setFontSize(7)
    doc.setFont('helvetica', 'bold')
    setColor(doc, TEXT)
    doc.text(member.name, x + 2, y + 6)

    x += nameColW
    for (let d = 0; d < 7; d++) {
      setFillColor(doc, CARD)
      doc.rect(x, y, dayColW, rowH, 'FD')

      const dayShifts = realShifts.filter(
        s => s.staffMemberId === member.id && s.dayOfWeek === d
      )
      if (dayShifts.length > 0) {
        const label = dayShifts.map(s => `${s.startTime}–${s.endTime}`).join(', ')
        doc.setFontSize(6.5)
        doc.setFont('helvetica', 'normal')
        setColor(doc, TEXT)
        doc.text(label, x + dayColW / 2, y + 6, { align: 'center' })
      }

      x += dayColW
    }

    y += rowH
  }

  // Footer
  const footerY = pageH - 10
  doc.setFontSize(7)
  doc.setFont('helvetica', 'italic')
  setColor(doc, MUTED)
  doc.text('Generated by Meridian', pageW / 2, footerY, { align: 'center' })

  return doc.output('blob')
}
